# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Samuel Drapeau
tagline: 'Personal Homepage'
description: >
    doing maths (still wondering why)<br>
    born and raised French<br>
    educated German<br>
    now in Shanghai

url: "https://www.samuel-drapeau.info/"
#baseurl: "/"

author: Samuel Drapeau

collections:
    articles:
        output: true
        permalink: /research/articles/:name/
    lectures:
        output: true
        permalink: /teaching/lectures/:name/

