# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Samuel Drapeau
tagline: 'Personal Homepage'
description: 'doing maths (still wondering why)<br>born and raised French<br>educated German<br>on my way to being Sinologized'

url: http://www.samuel-drapeau.info
baseurl: /

author: Samuel Drapeau


collections:
    articles:
        output: true
    lectures:
        output: true
