# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Samuel Drapeau
tagline: 'Personal Homepage'
description: >
    doing maths (still wondering why)<br>
    born and raised French<br>
    educated German<br>
    now in Shanghai

url: http://www.samuel-drapeau.info
baseurl: /

author: Samuel Drapeau

collections:
    articles:
        output: true
        permalink: /research/articles/:name/
    lectures:
        output: true
        permalink: /teaching/lectures/:name/

analytics:
    provider: google
    google: 
        tracking_id : 'UA-61158375-1'

